### ISSUE TITLE
KServe 0.8 release tracking

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#1906]
/kind feature

**Describe the solution you'd like**
KServe 0.8 release tracking:
RC release Date: 12/30/2021
Release Date: 1/14/2021

KServe Model Serving:
- [x] torchserve v2 protocol
  - https://github.com/kserve/kserve/pull/1870 @jagadeeshi2i 
- [X] Transformer -> Predictor gRPC support
  - https://github.com/kserve/kserve/pull/1933
- [X] MLServer 0.5 update
  - https://github.com/kserve/kserve/pull/1853 @adriangonz 
- [X] Scikit-Learn 1.0.1 and XGBoost 1.5.0 upgrade
  - https://github.com/kserve/kserve/pull/1954 @yuzisun 
- [X] Introduce ServingRuntime to single model serving @pvaneck @Suresh-Nakkeran 
  - https://github.com/kserve/kserve/pull/1901
  - https://github.com/kserve/kserve/pull/1926
- [ ] Introduce new storage spec @Tomcli 
  - https://github.com/kserve/kserve/pull/1899
- [X] Storage initializer fixes
  - https://github.com/kserve/kserve/pull/1883
  - https://github.com/kserve/kserve/pull/1940
- [X] Helm chart for KServe and ModelMesh @yuzisun 
  - https://github.com/kserve/kserve/pull/1878
- [X] KServe SDK features and fixes
  - https://github.com/kserve/kserve/pull/1949 @markwinter 
  - https://github.com/kserve/kserve/pull/1934 @markwinter 
  - https://github.com/kserve/kserve/pull/1918 @markwinter 

ModelMesh:
- [X] Multi-namespace support for ModelMesh
- [X] Improve rest proxy support
  - https://github.com/kserve/rest-proxy/pull/6

Models UI:
- [ ] Models Web App KServe migration @kimwnasptd   
  
  
Website:  
- [ ] Website doc update

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
