### ISSUE TITLE
KServe 0.9 release tracking

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#2168]
/kind feature

**Describe the solution you'd like**
KServe 0.9 release tracking:
RC release Date: 6/13/2022
Release Date: 6/27/2022

## KServe Model Serving:
- [X] Storage spec for unifying single model serving and model mesh
  - https://github.com/kserve/kserve/pull/1899 @Tomcli 
- [x] Transformer ModelMesh support
  - https://github.com/kserve/kserve/pull/2136 @chinhuang007 
- [x] Model Status API for unifying single model serving and model mesh
  - https://github.com/kserve/kserve/pull/2084 @pvaneck 
  - https://github.com/kserve/kserve/pull/2088 @Suresh-Nakkeran 
- [x] Inferece Graph v1alpha1 API and impmentation
  - https://github.com/kserve/kserve/pull/1910 @yuzisun @Iamlovingit 
- [X] KServe control plane HA
  - https://github.com/kserve/kserve/pull/2160 @Suresh-Nakkeran 
- [X] Enable inference protocol version auto selection for servingruntime 
  - https://github.com/kserve/kserve/pull/2118 @Suresh-Nakkeran 
- [x] Webhdfs storage uri support
  - https://github.com/kserve/kserve/pull/2077 @markwinter 
- [x] Azure file share support for storage initializer 
  - https://github.com/kserve/kserve/pull/1985 @laozc 
- [x] KServe Autoscaling spec API
  - https://github.com/kserve/kserve/pull/2082 @andyi2it 
- [X] KServe ingress class and domain template support for raw deployment mode
  - https://github.com/kserve/kserve/pull/2054 @pradithya 
  - https://github.com/kserve/kserve/pull/2049 @pradithya 

## ModelMesh:
- [X] OpenVINO model server support
  - https://github.com/kserve/modelmesh-runtime-adapter/pull/18 @tjohnson31415
- [x] Import ServingRuntime and InferenceService types from KServe 
  - https://github.com/kserve/modelmesh-serving/pull/146 @tjohnson31415 
  - https://github.com/kserve/modelmesh-serving/pull/140 @pvaneck 
- [x] Azure storage support for ModelMesh
  - https://github.com/kserve/modelmesh-runtime-adapter/pull/23 @pvaneck 

## Models UI:
- [x] Models Web App KServe 0.8 release support 
  - https://github.com/kserve/models-web-app/pull/35 @DavidSpek 

  
## Website:  
- [x] Website doc update

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
